version: 2
updates:
  - package-ecosystem: docker
    directory: '/web'
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: '/server'
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: '/proxy'
    schedule:
      interval: monthly
