name: Initialize Node.js, pnpm, and dependencies
inputs:
  cache:
    required: false
    default: true
  install:
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
    - name: Install Node.js
      uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
      with:
        node-version-file: .node-version
        cache: ${{ inputs.cache && 'pnpm' || '' }}
    - name: Install pnpm dependencies
      if: ${{ inputs.install != 'false' }}
      shell: bash
      run: pnpm install ${{ inputs.install }}
